name = "r2-registry"

workers_dev = false
main = "./index.ts"
compatibility_date = "2022-04-18"
compatibility_flags = ["streams_enable_constructors"]

## Production
[env.production]
name = "r2-registry-prod"
routes = [
  { pattern = "registry.joaquingimenez.com", custom_domain = true}
]
r2_buckets = [
  { binding = "REGISTRY", bucket_name = "docker-registry-prod" }
]

[env.production.vars]
JWT_REGISTRY_TOKENS_PUBLIC_KEY = ""

# Secrets:
# USERNAME/PASSWORD if you want username/password based auth


## Dev - For local dev using `npx wrangler dev`
[env.dev]
r2_buckets = [{ binding = "REGISTRY", bucket_name = "r2-image-registry-dev" }]
[env.dev.vars]
# REGISTRIES_JSON = "[{ \"registry\": \"http://localhost:9999\", \"password_env\": \"PASSWORD\", \"username\": \"hello\" }]"
USERNAME = "hello"
PASSWORD = "world"
# The necessary secrets are:
# Setup those secrets on .dev.vars in the root of the project
#
